### ISSUE TITLE
Create CLI interface to print symbol maps including the possible symbols

### ISSUE THREAD

**Issue by stefantaubert** [stefantaubert/text-utils#3]
Create a console interface which is able to print a given map and its possible symbols.
Input: Path to .json-file and optionally a .symbols-file
Output: pretty printed map | pretty printed symbols

# Example Map

```json
{
  "ɨ": "ʊ",
  "ɯ": "ʊ",
  "ʌ": "ʌ",
  "ʒ": "ʒ",
  "ʐ": "ʒ",
  "θ": "θ"
}
```

# Example Map Symbols

```txt
" "
"ʃ"
"ʊ"
"ʌ"
"ʒ"
"θ"
```

**Comment by jasminsternkopf** [comment]
please check the new pull request, I forgot to mention the issue in the corresponding commit

**Comment by stefantaubert** [comment]
Looks good. Please add:

- info if the mapping is the same symbol/not the same symbol.
- option "type" (with values "weights" or "inference") which changes the arrow direction (weights ->, inference <-)

**Comment by stefantaubert** [comment]
Please move `cli.py` to the `text_utls` folder and optimize it that `pipenv run python -m cli` throws no `KeyError`.

**Comment by stefantaubert** [comment]
Please also write instead of a space symbol `SPACE` and instead of nothing `NOTHING`.

**Comment by jasminsternkopf** [comment]
please check

**Comment by stefantaubert** [comment]
please:

- make use of the constants `SPACE` and `NOTHING`
- specify return types on all methods e.g. _init_parser in `cli.py`
- 33: create single function for text to bold text conversion
- 31: rename print_bold_if_true because one could also think if it is false then don't print it but you are printing it not bold instead
