### ISSUE TITLE
Create CLI interface to easily adjust symbol mappings

### ISSUE THREAD

**Issue by stefantaubert** [stefantaubert/text-utils#4]
Input: json map and symbols
Method: set mapping of destination symbol to symbol from symbols file or to empty
Output: updated map

# Example

Old map:

```json
{
  "ɨ": "ʊ",
  "ɯ": "ʊ",
  "ʌ": "ʌ",
  "ʒ": "ʒ",
  "ʐ": "ʒ",
  "θ": "θ"
}
```

Allowed symbols:
```txt
" "
"ʃ"
"ʊ"
"ʌ"
"ʒ"
"θ"
```

-> set "ʌ" to "ʒ"

New map:

```json
{
  "ɨ": "ʊ",
  "ɯ": "ʊ",
  "ʌ": "ʒ",
  "ʒ": "ʒ",
  "ʐ": "ʒ",
  "θ": "θ"
}
```

**Comment by jasminsternkopf** [comment]
I'll implement it in a way where the keys and the symbols will be numbered and printed and the user can decide via input which symbol should be assigned to which key (using the numbers corresponding to the symbol/key)

**Comment by jasminsternkopf** [comment]
please have a look at branch issue-4. I have to turn it in several smaller functions, but it would be nice to know whether it does what you expected. Maybe I have to work on the printed text, I'm still unsure about the interchanged keys/values

**Comment by stefantaubert** [comment]
Please add error handling if user inserts anything other than a number.
Adjust display so that the mapping to/from is displayed in parenthesis e.g. `20: t (→ t)` or print the symbol to choose in bold.
Add option to pass replace symbol without interactive mode e.g. `pipenv run python -m cli change_symbols --symbol_path "inference_map.symbols" --map_path "inference_map.json" --map "b" --to "a"` where `"b"` is the new value of key `"a"` in this case.

**Comment by stefantaubert** [comment]
Please provide the option to set the value to `NOTHING` (see #5).

**Comment by stefantaubert** [comment]
Please also provide an option to reverse the arrow like in #5

**Comment by jasminsternkopf** [comment]
parameter defining the arrow direction is required, not optional

**Comment by jasminsternkopf** [comment]
> Add option to pass replace symbol without interactive mode e.g. `pipenv run python -m cli change_symbols --symbol_path "inference_map.symbols" --map_path "inference_map.json" --map "b" --to "a"` where `"b"` is the new value of key `"a"` in this case.
should not print map again or ask for further revisions, just doing this one change and saving the results

**Comment by jasminsternkopf** [comment]
I'll print the lines where key and value are the same in bold, as in issue #3.

**Comment by stefantaubert** [comment]
Please adjust acconding to #3 and:

- 85: parenthesize conditions
- 77: rename `map` because `map` is a build-in python function `Redefining built-in 'map'pylint(redefined-builtin)`
- 22: rename `print_bold_if_true` because one could also think if it is false then don't print it but you are printing it not bold instead
